### ISSUE TITLE
skysat triplet pipeline

### ISSUE THREAD

**Issue by Bea07** [uw-cryo/skysat_stereo#14]
From the line 147 to the line 168 of the skysat_triplet_pipeline.py, is the indentation correct?

**Comment by ShashankBice** [comment]
Hi Bea07,
I think the indentation is fine, did you have a specific problem which I could help with ?
The idea here is that part of the program should be executed when any of the specific individual steps is invoked by the user. This block computes the local EPSG code, and clips the DEM for co-registration/orthorectification to the extent of the triplet collection footprint. 
I would be open to suggestions, I am still planning to refine the code base so these steps can be called as functions, rather than subprocess calls, but it will take some time.
Cheers,
Shashank

**Comment by Bea07** [comment]
Thank you Shashank,
indeed with your explication now I understood better, thank you very much.
In this sense, I can consider the issue closed. I am processing the pipeline on a pc with lower computation capability so I am running it part by part which means I can change the indentation for those lines, including them in the first step of the pipeline, and than proceeding with the second step.
Cheers,
Bea

**Comment by ShashankBice** [comment]
Hi Bea,
Sounds great ! Let me know how your experiments go, would be very interested in gawking your results ! Also, if you have  suggestions/improvements pass them to me as well :)  

Thanks,
Shashank

**Comment by Bea07** [comment]
Dear Shashank,
I would like to ask you some info regarding the pipeline.
I think your work is really promising and , as well, we are interested in
achieving a better understanding of skysat products.
I would like to know if there are some requirements for the DSM as
reference that is given as input, and what can cause a worse DSM quality
(lower resolution than the skysat L1A/L1B scenes) in the output DSM.
Moreover I would ask if as input I can use a DSM that is not covering the
total area of Skysat acquisition, or in case covering the nodata area with
a lower res DSM.
Did you test the pipeline over other areas, i.e. not glaciers, acquired by
Skysat? Did you encounter any difference in your output?
Thank you very much for your support
Cheers,
Beatrice



Il giorno mar 27 lug 2021 alle ore 19:05 Shashank Bhushan <
***@***.***> ha scritto:

**Comment by ShashankBice** [comment]
Hi Beatrice,
We outline the reference DEM considerations in Section 5.3.3 here: https://www.sciencedirect.com/science/article/pii/S0924271620303506. 
For most of the steps we would require a reference DEM that covers the entire area of triplet collection. For Co-registration step, the DEM can cover a slightly smaller area, but for best results i would still suggest a DEM which covers the full area.
I have mostly run the pipeline over natural features, which have encompassed glaciers, stream channels, steep mountains, crater walls and flat desert areas. I also did run some experiments over natural man-made city features in Rome and was able to reconstruct the bigger building structures with ASP's block matching algorithm. The MGM algorithm in the city triplet test case produced a less sharp result. This city experiment was carried out during my internship at Planet and so I do not have those results to share though :) 
Now the most pressing question at the last: It is difficult to achieve the resolution of input satellite imagery in the output DSM, as the conventional kernel based disparity computation algorithm do not provide totally independent per-pixel measurements. In general the resolution of the DEM can be expected to be 3 to 4 time the resolution of our bi/tri-stereo imagery.  See some discussion here: https://groups.google.com/g/ames-stereo-pipeline-support/c/nNESoJGqeZs/m/0PRyLHVlAQAJ. With that said, we can use leverage the video dataset to generate multiple overlapping point cloud and then perform joint gridding which can potentially result in a finer resolution DEM, but I still have to do that test in a quantitative manner :) 

If you could share what area you are working on and the difficulties you are facing (if any), I can potentially provide more streamlined advice :) 

Thanks,
Shashank
